"""HAND-WRITTEN golden expectations for the seed encounters (B0). @k signs these off at CP0.

Written from the rule catalog (build context Section 8.2, 8.5, 8.6, 8.8, 8.9, 14.1), NOT
generated by an engine. ``materialize.py`` only resolves each quoted span to its offsets,
computes ids/hashes with contracts.ids, validates against the frozen contract, and
cross-checks the declared scope and counts. It makes no rule decision.

After CP0 only a CCR changes this file (docs/contract_changes/CCR-NN.md).

Conventions used below (see fixtures/expected/README.md for the full list):
- E(source_key, version, role, quote): ``quote`` must be exactly one statement span
  (contracts/spans.py) of that version's extracted text. Role: claim = earlier side /
  the statement the flag is about; counter_claim = later side; origin = where carried
  text first appeared; suppressor = a documented response; trigger = what triggered a
  bubble; extraction_gap = unread PDF page (quote "").
- Owners and affected contributors are staff keys from fixtures/author_fixtures.py.
  affected = (authors of evidence sources + care-team pharmacists for
  responsible_clinician_plus_pharmacy rules) minus the owner.
- New flags cite the latest in-scope version. An EXISTING flag keeps citing the version
  it cited while its normalised facts still hold; if a cited source has a newer in-scope
  version it sets source_changed_since_flag (revision +1, evidence_revision unchanged).
- ``{src:key}`` in a subject key is replaced with that source's source_id.
"""

from __future__ import annotations


def E(src: str, ver: int, role: str, quote: str, rev: int = 1) -> dict:
    return {"src": src, "ver": ver, "role": role, "quote": quote, "rev": rev}


def GAP(src: str, ver: int = 1, page: int = 1) -> dict:
    return {"src": src, "ver": ver, "role": "extraction_gap", "quote": "", "page": page, "rev": 1}


# ---------------------------------------------------------------------------
# Reusable evidence (ENC-A1)
# ---------------------------------------------------------------------------

K_OBS = E("bloods", 1, "claim", "Potassium 6.4 mmol/L")
K_TRIGGER = E("bloods", 1, "trigger", "Potassium 6.4 mmol/L")
K_RESP_REVIEW = "K 6.4 reviewed, treated per protocol"  # review + treatment, same analyte, 15:30
K_RESP_REPEAT = "Repeat K sent; Dr Lim to review result by 18:00"  # repeat (+ review), 15:30

NKDA = E("adm_nursing", 1, "claim", "Allergies: NKDA (patient reported)")
PEN = "Allergy: Penicillin allergy \u2014 rash (per GP records)"  # identical text in medrec v1 and v2

AML_WARD = E("ward_round", 1, "claim", "Amlodipine 5 mg OD")
GP_LIST_V1 = "GP list: amlodipine 10 mg once daily; metformin 500 mg twice daily"
GP_LIST_V2 = "GP list dated 01/09/2026: amlodipine 10 mg once daily; metformin 500 mg twice daily"

CULTURE = E("ward_round", 1, "claim", "Blood culture sent, awaiting result")
CULTURE_TRIGGER = E("ward_round", 1, "trigger", "Blood culture sent, awaiting result")

STABLE_EVIDENCE = [
    E("sw", 1, "claim", "Patient stable"),
    E("ward_round", 1, "origin", "Patient stable"),
    E("obs", 1, "counter_claim", "SpO2 89% on room air, RR 26"),
]

# ---------------------------------------------------------------------------
# Reusable text (hand-written; B1 renders equivalent text from rulesets/v1.json.
# Text is NOT part of exact comparison, but it IS linted for forbidden phrases.)
# ---------------------------------------------------------------------------

R_CRIT_1130 = ('Blood results (Nurse Tan, 11:15) records "Potassium 6.4 mmol/L". No later review, repeat, '
               "treatment, escalation or transfer for this result is documented in the supplied sources up to 11:30.")
R_ALG = ('Admission nursing assessment (Nurse Tan, 08:40) states "Allergies: NKDA (patient reported)" while '
         f'Medication reconciliation (Pharmacist Ong, 10:30) names "{PEN}".')
R_DOSE_V1 = ('Ward round (Dr Lim, 09:00) records "Amlodipine 5 mg OD"; Medication reconciliation (Pharmacist Ong, '
             f'10:30) records "{GP_LIST_V1}". No explicit change links them.')
R_DOSE_V2 = ('Ward round (Dr Lim, 09:00) records "Amlodipine 5 mg OD"; Medication reconciliation (Pharmacist Ong, '
             f'10:30) records "{GP_LIST_V2}". No explicit change links them.')
R_PEND = ('Ward round (Dr Lim, 09:00) records "Blood culture sent, awaiting result" without an explicit owner or '
          "timing in the supplied sources.")
R_PDF = ("Scanned outside lab report (Nurse Ravi, 12:10) has extraction status no_text_layer. Its content has not "
         "been checked; answers about absent documentation are limited until it is reviewed manually or by approved OCR.")
R_DIFF = ('Discharge planning (SW Goh, 16:00) repeats "Patient stable" from Ward round (Dr Lim, 09:00); Afternoon '
          'observations (Nurse Ravi, 13:00) records "SpO2 89% on room air, RR 26" in between.')
Q_DIFF = 'Is the 16:00 "Patient stable" statement current?'

U_CONFLICT = ("The supplied sources disagree. Only a clinician's decision can settle which entry is correct; the "
              "checker does not choose between sources.")
U_DOCUMENTED = ("Documented in the cited source. The checker matched wording only and has not verified the clinical "
                "content.")
U_PDF = "The checker cannot answer this from the supplied text; a person needs to check the document."
U_CF = ("The checker cannot tell whether a repeated statement is current; the note's author or the responsible "
        "clinician needs to confirm.")


def U_ABSENT(n: int, cutoff: str) -> str:
    return (f"Searched {n} supplied sources up to {cutoff} for the listed terms and found no matching entry. This "
            "describes the supplied record only, not what took place.")


U_INCOMPLETE = ("1 in-scope source could not be read: Scanned outside lab report (Nurse Ravi, 12:10). The answer "
                "stays incomplete until it is reviewed manually or by approved OCR.")

CRIT_TERMS = ["analyte:potassium", "cue:response_review", "cue:response_repeat", "cue:response_treatment",
              "cue:response_escalation", "cue:response_transfer"]

# ---------------------------------------------------------------------------
# Scenarios
# ---------------------------------------------------------------------------

SCOPE_1130 = [("referral", 1), ("adm_nursing", 1), ("ward_round", 1), ("medrec", 1), ("bloods", 1)]
SCOPE_1600 = [("referral", 1), ("adm_nursing", 1), ("ward_round", 1), ("medrec", 2), ("bloods", 1),
              ("lab_pdf", 1), ("obs", 1), ("physio", 1), ("clin_review", 1), ("sw", 1)]

ENC_A1_1130 = {
    "encounter": "ENC-A1", "cutoff": "11:30", "evaluated_at": "11:31", "prior": None,
    "scope": SCOPE_1130, "outcome": "completed",
    "flags": [
        {"rule": "CRIT-001", "subject": "analyte:potassium", "tier": 1, "owner": "lim", "affected": ["tan"],
         "evidence": [K_OBS], "reason": R_CRIT_1130},
        {"rule": "ALG-001", "subject": "allergen:penicillin", "tier": 1, "owner": "lim", "affected": ["ong", "tan"],
         "evidence": [NKDA, E("medrec", 1, "counter_claim", PEN)], "reason": R_ALG},
        {"rule": "DOSE-001", "subject": "drug:amlodipine", "tier": 2, "owner": "lim", "affected": ["ong"],
         "evidence": [AML_WARD, E("medrec", 1, "counter_claim", GP_LIST_V1)], "reason": R_DOSE_V1},
        {"rule": "PEND-001", "subject": "test:blood_culture", "tier": 2, "owner": "lim", "affected": [],
         "evidence": [CULTURE], "reason": R_PEND},
    ],
    "must_not_flag": [
        ("DOSE-001", "drug:metformin", '"500 mg BD" (09:00) and "500 mg twice daily" (10:30) are the same regimen after frequency normalisation.'),
        ("CRIT-001", "analyte:sodium", "Sodium 138 mmol/L is inside the placeholder critical range."),
        ("PDF-001", "source:{src:referral}", "The referral PDF has a complete text layer."),
        ("OWN-001", "encounter", "A responsible clinician (Dr Lim) is recorded."),
        ("DOSE-002", "*", "Every number + dose unit in scope is attached to a parsed regimen."),
        ("DIFF-001", "*", '"Patient stable" occurs once in scope; nothing is carried forward yet.'),
    ],
    "must_not_suppress_note": '"Not yet reviewed by medical team" (11:15) is a NEGATED response and must not suppress CRIT-001.',
    "bubbles": [
        {"template": "q_allergy_which_correct", "subject": "allergen:penicillin", "status": "conflicting",
         "flag": ("ALG-001", "allergen:penicillin"), "evidence": "flag", "question": "Which allergy entry is correct?",
         "uncertainty": U_CONFLICT},
        {"template": "q_crit_response", "subject": "analyte:potassium", "status": "not_documented_in_supplied_sources",
         "flag": ("CRIT-001", "analyte:potassium"), "evidence": [K_TRIGGER], "terms": CRIT_TERMS,
         "question": "Was the critical potassium reviewed or repeated?", "uncertainty": U_ABSENT(5, "11:30")},
        {"template": "q_ecg_documented", "subject": "analyte:potassium", "status": "not_documented_in_supplied_sources",
         "flag": ("CRIT-001", "analyte:potassium"), "evidence": [K_TRIGGER], "terms": ["test:ecg"],
         "question": "Is an ECG documented for this episode?", "uncertainty": U_ABSENT(5, "11:30")},
        {"template": "q_dose_current", "subject": "drug:amlodipine", "status": "conflicting",
         "flag": ("DOSE-001", "drug:amlodipine"), "evidence": "flag", "question": "Which amlodipine dose is current?",
         "uncertainty": U_CONFLICT},
        {"template": "q_pending_owner", "subject": "test:blood_culture", "status": "not_documented_in_supplied_sources",
         "flag": ("PEND-001", "test:blood_culture"), "evidence": [CULTURE_TRIGGER],
         "terms": ["test:blood_culture", "cue:owner"], "question": "Who owns the pending blood culture result?",
         "uncertainty": U_ABSENT(5, "11:30")},
    ],
    "required_changes": [
        ("reworded", "drug:metformin", ("ward_round", 1, "Metformin 500 mg BD"), ("medrec", 1, GP_LIST_V1)),
    ],
    "summary_open_priorities": [("CRIT-001", "analyte:potassium"), ("ALG-001", "allergen:penicillin"),
                                ("DOSE-001", "drug:amlodipine"), ("PEND-001", "test:blood_culture")],
    "summary_top_questions": [("q_allergy_which_correct", "allergen:penicillin"),
                              ("q_crit_response", "analyte:potassium"), ("q_ecg_documented", "analyte:potassium")],
    "closure": {"status": "blocked", "tier1": [("CRIT-001", "analyte:potassium"), ("ALG-001", "allergen:penicillin")],
                "tier2": [("DOSE-001", "drug:amlodipine"), ("PEND-001", "test:blood_culture")], "tier3_count": 0},
}

ENC_A1_1600 = {
    "encounter": "ENC-A1", "cutoff": "16:00", "evaluated_at": "16:01", "prior": None,
    "scope": SCOPE_1600, "outcome": "completed_with_extraction_gaps",
    "flags": [
        {"rule": "ALG-001", "subject": "allergen:penicillin", "tier": 1, "owner": "lim", "affected": ["ong", "tan"],
         "evidence": [NKDA, E("medrec", 2, "counter_claim", PEN)], "reason": R_ALG},
        {"rule": "DOSE-001", "subject": "drug:amlodipine", "tier": 2, "owner": "lim", "affected": ["ong"],
         "evidence": [AML_WARD, E("medrec", 2, "counter_claim", GP_LIST_V2)], "reason": R_DOSE_V2},
        {"rule": "PEND-001", "subject": "test:blood_culture", "tier": 2, "owner": "lim", "affected": [],
         "evidence": [CULTURE], "reason": R_PEND},
        {"rule": "PDF-001", "subject": "source:{src:lab_pdf}", "tier": 2, "owner": "ravi", "affected": [],
         "evidence": [GAP("lab_pdf")], "reason": R_PDF},
        {"rule": "DIFF-001", "subject": "status:stable@source:{src:sw}", "tier": 3, "owner": "goh",
         "affected": ["lim", "ravi"], "evidence": STABLE_EVIDENCE, "reason": R_DIFF, "question": Q_DIFF},
    ],
    "must_not_flag": [
        ("CRIT-001", "analyte:potassium", 'Suppressed at evaluation time: 15:30 "K 6.4 reviewed, treated per protocol" is later, new (not carried forward), non-negated and names the same analyte (Section 8.5).'),
        ("DOSE-001", "drug:metformin", '15:30 "Metformin increased to 1 g BD" is an explicit change by the responsible clinician (L3), not a contradiction.'),
        ("PEND-001", "analyte:potassium", '"Repeat K sent; Dr Lim to review result by 18:00" names an owner AND a time in the same statement.'),
        ("CRIT-001", "analyte:spo2", "SpO2 89% is a deterioration marker in registry v1 (feeds DIFF-001/DET-001), not a critical threshold. Governance question recorded in docs/decisions/B0.md."),
        ("CRIT-001", "analyte:respiratory_rate", "RR 26 is a deterioration marker in registry v1, not a critical threshold."),
        ("PDF-001", "source:{src:referral}", "The referral PDF has a complete text layer."),
        ("OWN-001", "encounter", "A responsible clinician (Dr Lim) is recorded."),
        ("DOSE-002", "*", "Every number + dose unit in scope is attached to a parsed regimen (1 g BD included)."),
    ],
    "must_not_suppress_note": ("The medrec v2 amendment (15:45) is a new VERSION of the 10:30 source, not a new source: exactly "
                               'one ALG-001 and one DOSE-001 (L1). Physio "Next step ... tomorrow AM" and SW "Next step ... '
                               'tomorrow 10:00" carry no pending cue and name no test, result or referral: the only PEND-001 '
                               "is the blood culture."),
    "bubbles": [
        {"template": "q_allergy_which_correct", "subject": "allergen:penicillin", "status": "conflicting",
         "flag": ("ALG-001", "allergen:penicillin"), "evidence": "flag", "question": "Which allergy entry is correct?",
         "uncertainty": U_CONFLICT},
        {"template": "q_crit_response", "subject": "analyte:potassium", "status": "documented", "flag": None,
         "evidence": [K_TRIGGER, E("clin_review", 1, "suppressor", K_RESP_REVIEW),
                      E("clin_review", 1, "suppressor", K_RESP_REPEAT)],
         "question": "Was the critical potassium reviewed or repeated?", "uncertainty": U_DOCUMENTED},
        {"template": "q_ecg_documented", "subject": "analyte:potassium", "status": "incomplete_extraction", "flag": None,
         "evidence": [K_TRIGGER, GAP("lab_pdf")], "terms": ["test:ecg"],
         "question": "Is an ECG documented for this episode?", "uncertainty": U_INCOMPLETE},
        {"template": "q_dose_current", "subject": "drug:amlodipine", "status": "conflicting",
         "flag": ("DOSE-001", "drug:amlodipine"), "evidence": "flag", "question": "Which amlodipine dose is current?",
         "uncertainty": U_CONFLICT},
        {"template": "q_pending_owner", "subject": "test:blood_culture", "status": "incomplete_extraction",
         "flag": ("PEND-001", "test:blood_culture"), "evidence": [CULTURE_TRIGGER, GAP("lab_pdf")],
         "terms": ["test:blood_culture", "cue:owner"], "question": "Who owns the pending blood culture result?",
         "uncertainty": U_INCOMPLETE},
        {"template": "q_pdf_manual_review", "subject": "source:{src:lab_pdf}", "status": "requires_human_review",
         "flag": ("PDF-001", "source:{src:lab_pdf}"), "evidence": "flag",
         "question": "Has Scanned outside lab report (Nurse Ravi, 12:10) been reviewed manually or by approved OCR?",
         "uncertainty": U_PDF},
        {"template": "q_carried_forward_current", "subject": "status:stable@source:{src:sw}",
         "status": "requires_human_review", "flag": ("DIFF-001", "status:stable@source:{src:sw}"), "evidence": "flag",
         "question": Q_DIFF, "uncertainty": U_CF},
    ],
    "required_changes": [
        ("reworded", "drug:metformin", ("ward_round", 1, "Metformin 500 mg BD"), ("medrec", 2, GP_LIST_V2)),
        ("explicit_change", "drug:metformin", ("medrec", 2, GP_LIST_V2), ("clin_review", 1, "Metformin increased to 1 g BD")),
        ("carried_forward", "status:stable", ("ward_round", 1, "Patient stable"), ("sw", 1, "Patient stable")),
    ],
    "summary_open_priorities": [("ALG-001", "allergen:penicillin"), ("DOSE-001", "drug:amlodipine"),
                                ("PEND-001", "test:blood_culture"), ("PDF-001", "source:{src:lab_pdf}")],
    "summary_top_questions": [("q_allergy_which_correct", "allergen:penicillin"),
                              ("q_ecg_documented", "analyte:potassium"), ("q_dose_current", "drug:amlodipine")],
    "closure": {"status": "blocked", "tier1": [("ALG-001", "allergen:penicillin")],
                "tier2": [("DOSE-001", "drug:amlodipine"), ("PEND-001", "test:blood_culture"),
                          ("PDF-001", "source:{src:lab_pdf}")], "tier3_count": 1},
}

# Same cutoff, but the engine has seen the 11:30 flags (snapshot.prior_flags = the 11:30
# golden flags, no decisions). This is the live-app path: checks rerun on every source change.
ENC_A1_1600_RERUN = {
    "encounter": "ENC-A1", "cutoff": "16:00", "evaluated_at": "16:01", "prior": "ENC-A1_1130",
    "scope": SCOPE_1600, "outcome": "completed_with_extraction_gaps",
    "flags": [
        # Seen at 11:30, response now documented -> SUPERSEDED (never resolved by the engine).
        # Tier 1 superseded still blocks closure until Dr Lim confirms (resolve, reason code).
        {"rule": "CRIT-001", "subject": "analyte:potassium", "tier": 1, "owner": "lim", "affected": ["tan"],
         "state": "superseded", "revision": 2, "evidence_revision": 2, "first_run": "ENC-A1_1130",
         "evidence": [K_OBS, E("clin_review", 1, "suppressor", K_RESP_REVIEW, rev=2),
                      E("clin_review", 1, "suppressor", K_RESP_REPEAT, rev=2)], "reason": R_CRIT_1130},
        # Cited medrec v1; v2 amendment now in scope with the same normalised facts ->
        # keep the v1 citation, mark source changed (side-by-side in the UI).
        {"rule": "ALG-001", "subject": "allergen:penicillin", "tier": 1, "owner": "lim", "affected": ["ong", "tan"],
         "revision": 2, "source_changed": True, "first_run": "ENC-A1_1130",
         "evidence": [NKDA, E("medrec", 1, "counter_claim", PEN)], "reason": R_ALG},
        {"rule": "DOSE-001", "subject": "drug:amlodipine", "tier": 2, "owner": "lim", "affected": ["ong"],
         "revision": 2, "source_changed": True, "first_run": "ENC-A1_1130",
         "evidence": [AML_WARD, E("medrec", 1, "counter_claim", GP_LIST_V1)], "reason": R_DOSE_V1},
        # Unchanged since 11:30.
        {"rule": "PEND-001", "subject": "test:blood_culture", "tier": 2, "owner": "lim", "affected": [],
         "first_run": "ENC-A1_1130", "evidence": [CULTURE], "reason": R_PEND},
        # New in this run.
        {"rule": "PDF-001", "subject": "source:{src:lab_pdf}", "tier": 2, "owner": "ravi", "affected": [],
         "evidence": [GAP("lab_pdf")], "reason": R_PDF},
        {"rule": "DIFF-001", "subject": "status:stable@source:{src:sw}", "tier": 3, "owner": "goh",
         "affected": ["lim", "ravi"], "evidence": STABLE_EVIDENCE, "reason": R_DIFF, "question": Q_DIFF},
    ],
    "must_not_flag": [
        ("DOSE-001", "drug:metformin", "Explicit change (L3)."),
        ("PEND-001", "analyte:potassium", "Owner and time in the same statement."),
    ],
    "must_not_suppress_note": "CRIT-001 must be superseded, not resolved or dismissed, and must still block closure.",
    "bubbles": "same_as:ENC-A1_1600 except flag links",
    "bubbles_override": {
        # Critical-observation bubbles link to the CRIT-001 flag when one exists (any state).
        ("q_crit_response", "analyte:potassium"): {"flag": ("CRIT-001", "analyte:potassium")},
        ("q_ecg_documented", "analyte:potassium"): {"flag": ("CRIT-001", "analyte:potassium")},
        # Conflict bubbles carry the flag's current evidence (still the v1 citation).
        ("q_allergy_which_correct", "allergen:penicillin"): {"evidence": "flag"},
        ("q_dose_current", "drug:amlodipine"): {"evidence": "flag"},
    },
    "required_changes": "same_as:ENC-A1_1600",
    "summary_open_priorities": [("CRIT-001", "analyte:potassium"), ("ALG-001", "allergen:penicillin"),
                                ("DOSE-001", "drug:amlodipine"), ("PEND-001", "test:blood_culture"),
                                ("PDF-001", "source:{src:lab_pdf}")],
    "summary_top_questions": [("q_allergy_which_correct", "allergen:penicillin"),
                              ("q_ecg_documented", "analyte:potassium"), ("q_dose_current", "drug:amlodipine")],
    "closure": {"status": "blocked", "tier1": [("CRIT-001", "analyte:potassium"), ("ALG-001", "allergen:penicillin")],
                "tier2": [("DOSE-001", "drug:amlodipine"), ("PEND-001", "test:blood_culture"),
                          ("PDF-001", "source:{src:lab_pdf}")], "tier3_count": 1},
}

ENC_B1_1600 = {
    "encounter": "ENC-B1", "cutoff": "16:00", "evaluated_at": "16:01", "prior": None,
    "scope": [("nursing", 1)], "outcome": "completed",
    "flags": [],
    "must_not_flag": [
        ("ALG-001", "*", "NKDA alone, with no named allergy anywhere in scope, is not a conflict."),
        ("*", "*", "Benign single note: no rule applies."),
    ],
    "must_not_suppress_note": None,
    "bubbles": [],
    "required_changes": [],
    "summary_open_priorities": [],
    "summary_top_questions": [],
    "closure": {"status": "clear", "tier1": [], "tier2": [], "tier3_count": 0},
}

SCENARIOS: dict[str, dict] = {
    "ENC-A1_1130": ENC_A1_1130,
    "ENC-A1_1600": ENC_A1_1600,
    "ENC-A1_1600_rerun": ENC_A1_1600_RERUN,
    "ENC-B1_1600": ENC_B1_1600,
}
