// GENERATED from docs/openapi.json sha256=085929ae3b053a7df8af604d7b13267d8fa0fc9c452e7b312aa92349ebda4a25 by scripts/gen_ts_types.py. Do not edit; run `make types`.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/aggregate/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate */
        get: operations["aggregate_api_aggregate_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Status */
        get: operations["ai_status_api_ai_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description Needs the session cookie but not the workspace header (opened in a new tab); the token
         *     is bound to the issuing staff member and workspace and re-checked against the care team.
         */
        get: operations["get_document_api_documents__document_token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Encounters */
        get: operations["list_encounters_api_encounters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Encounter */
        get: operations["get_encounter_api_encounters__encounter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/bubbles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bubbles */
        get: operations["list_bubbles_api_encounters__encounter_id__bubbles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/check-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Checks */
        post: operations["run_checks_api_encounters__encounter_id__check_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/check-runs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Run */
        get: operations["latest_run_api_encounters__encounter_id__check_runs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/closure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Closure */
        get: operations["get_closure_api_encounters__encounter_id__closure_get"];
        put?: never;
        /** Attempt Close */
        post: operations["attempt_close_api_encounters__encounter_id__closure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_api_encounters__encounter_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Flags */
        get: operations["list_flags_api_encounters__encounter_id__flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/flags/{flag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Flag */
        get: operations["get_flag_api_encounters__encounter_id__flags__flag_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/flags/{flag_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_api_encounters__encounter_id__flags__flag_id__decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/glance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Glance */
        get: operations["get_glance_api_encounters__encounter_id__glance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/source-versions/{source_version_id}/document-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Document Token */
        post: operations["document_token_api_encounters__encounter_id__source_versions__source_version_id__document_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/source-versions/{source_version_id}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source Text */
        get: operations["get_source_text_api_encounters__encounter_id__source_versions__source_version_id__text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Text Source */
        post: operations["add_text_source_api_encounters__encounter_id__sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/sources/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Pdf Source */
        post: operations["add_pdf_source_api_encounters__encounter_id__sources_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encounters/{encounter_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_encounters__encounter_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Session */
        get: operations["current_session_api_session_get"];
        put?: never;
        /** Login */
        post: operations["login_api_session_post"];
        /** Logout */
        delete: operations["logout_api_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Workspace */
        post: operations["new_workspace_api_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Reset Workspace */
        delete: operations["reset_workspace_api_workspaces_current_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AIDraftStatus
         * @enum {string}
         */
        AIDraftStatus: "disabled" | "unavailable_fallback" | "rejected_fallback" | "validated";
        /** AIStatusView */
        AIStatusView: {
            /** Detail */
            detail: string;
            status: components["schemas"]["AIDraftStatus"];
        };
        /**
         * AbsenceFinding
         * @description An absence answer is a claim about a SEARCH, not about the patient.
         *     Cannot be constructed without its search scope.
         */
        AbsenceFinding: {
            /**
             * Cutoff
             * Format: date-time
             */
            cutoff: string;
            /** Question Template Id */
            question_template_id: string;
            /** Registry Version */
            registry_version: string;
            /** Sources Searched */
            sources_searched: components["schemas"]["SearchedSource"][];
            /**
             * Status
             * @enum {string}
             */
            status: "not_documented_in_supplied_sources" | "incomplete_extraction";
            /** Terms Searched */
            terms_searched: string[];
        };
        /** AddTextSourceRequest */
        AddTextSourceRequest: {
            /** Author Staff Id */
            author_staff_id: string;
            discipline: components["schemas"]["Discipline"];
            /** External Id */
            external_id?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /**
             * Identifier Namespace
             * @default noteguard-paste
             */
            identifier_namespace: string;
            /** Source Id */
            source_id?: string | null;
            /**
             * Source Time
             * Format: date-time
             */
            source_time: string;
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /** Body_add_pdf_source_api_encounters__encounter_id__sources_pdf_post */
        Body_add_pdf_source_api_encounters__encounter_id__sources_pdf_post: {
            /** Author Staff Id */
            author_staff_id: string;
            /** Discipline */
            discipline: string;
            /** External Id */
            external_id?: string | null;
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Identifier Namespace */
            identifier_namespace?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Source Time */
            source_time: string;
            /** Title */
            title: string;
        };
        /** BubbleList */
        BubbleList: {
            /** @default disabled */
            ai_status: components["schemas"]["AIDraftStatus"];
            /** Bubbles */
            bubbles: components["schemas"]["QuestionBubble"][];
            /**
             * Cutoff
             * Format: date-time
             */
            cutoff: string;
        };
        /**
         * BubbleStatus
         * @description The ONLY answers a question bubble may give (Section 8.8).
         * @enum {string}
         */
        BubbleStatus: "documented" | "not_documented_in_supplied_sources" | "conflicting" | "incomplete_extraction" | "requires_human_review";
        /** CareTeamMembership */
        CareTeamMembership: {
            /** Encounter Id */
            encounter_id: string;
            /** Staff Id */
            staff_id: string;
            team_role: components["schemas"]["TeamRole"];
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
        };
        /**
         * ChangeKind
         * @enum {string}
         */
        ChangeKind: "new" | "explicit_change" | "reworded" | "carried_forward" | "removed";
        /**
         * ChangeView
         * @description Diff chip data: '+ new', '~ explicit change', '= carried forward', '! contradicts'.
         */
        ChangeView: {
            from_evidence: components["schemas"]["Evidence"] | null;
            kind: components["schemas"]["ChangeKind"];
            /** Subject Key */
            subject_key: string;
            to_evidence: components["schemas"]["Evidence"] | null;
        };
        /** CheckRun */
        CheckRun: {
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Encounter Id */
            encounter_id: string;
            outcome: components["schemas"]["CheckRunOutcome"];
            /** Registry Version */
            registry_version: string;
            /** Ruleset Version */
            ruleset_version: string;
            /** Run Id */
            run_id: string;
            /**
             * Source Cutoff
             * Format: date-time
             */
            source_cutoff: string;
            /** Source Set Hash */
            source_set_hash: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /**
         * CheckRunOutcome
         * @enum {string}
         */
        CheckRunOutcome: "completed" | "completed_with_extraction_gaps" | "failed";
        /** CheckRunRequest */
        CheckRunRequest: {
            /**
             * Cutoff
             * Format: date-time
             */
            cutoff: string;
        };
        /** CheckRunView */
        CheckRunView: {
            /** Changes */
            changes: components["schemas"]["ChangeView"][];
            /** Flags */
            flags: components["schemas"]["Flag"][];
            run: components["schemas"]["CheckRun"];
        };
        /** ClosureBlocker */
        ClosureBlocker: {
            /** Flag Id */
            flag_id: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Owner Staff Id */
            owner_staff_id: string;
            state: components["schemas"]["FlagState"];
            tier: components["schemas"]["Tier"];
        };
        /**
         * ClosureStatus
         * @enum {string}
         */
        ClosureStatus: "blocked" | "clear_with_open_tier2" | "clear";
        /** ClosureView */
        ClosureView: {
            /**
             * Cutoff
             * Format: date-time
             */
            cutoff: string;
            /** Decisions */
            decisions: components["schemas"]["Decision"][];
            /** Encounter Id */
            encounter_id: string;
            status: components["schemas"]["ClosureStatus"];
            /** Tier1 Blockers */
            tier1_blockers: components["schemas"]["ClosureBlocker"][];
            /** Tier2 Open */
            tier2_open: components["schemas"]["ClosureBlocker"][];
            /** Tier3 Open Count */
            tier3_open_count: number;
        };
        /**
         * Decision
         * @description Append-only record of a human decision.
         */
        Decision: {
            action: components["schemas"]["DecisionAction"];
            actor_role: components["schemas"]["Role"];
            /** Actor Staff Id */
            actor_staff_id: string;
            /**
             * Adjudicated Evidence
             * @default []
             */
            adjudicated_evidence: components["schemas"]["EvidenceRef"][];
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Decision Id */
            decision_id: string;
            edit_field?: components["schemas"]["EditField"] | null;
            /** Encounter Id */
            encounter_id: string;
            /** Expected Revision */
            expected_revision: number;
            /** Flag Id */
            flag_id: string;
            from_state: components["schemas"]["FlagState"];
            /** New Owner Staff Id */
            new_owner_staff_id?: string | null;
            prepared_check?: components["schemas"]["PreparedCheck"] | null;
            /** Rationale Text */
            rationale_text?: string | null;
            reason_code?: components["schemas"]["ReasonCode"] | null;
            /** Resulting Revision */
            resulting_revision: number;
            to_state: components["schemas"]["FlagState"];
        };
        /**
         * DecisionAction
         * @enum {string}
         */
        DecisionAction: "accept" | "edit" | "reassign" | "mark_ready_for_clinician" | "dismiss" | "resolve";
        /**
         * DecisionRequest
         * @description What a client sends. Rationale text is held in memory only, never logged.
         */
        DecisionRequest: {
            action: components["schemas"]["DecisionAction"];
            /**
             * Adjudicated Evidence
             * @default []
             */
            adjudicated_evidence: components["schemas"]["EvidenceRef"][];
            /** Duplicate Of Flag Id */
            duplicate_of_flag_id?: string | null;
            edit_field?: components["schemas"]["EditField"] | null;
            /** Expected Revision */
            expected_revision: number;
            /** New Owner Staff Id */
            new_owner_staff_id?: string | null;
            prepared_check?: components["schemas"]["PreparedCheck"] | null;
            /** Rationale Text */
            rationale_text?: string | null;
            reason_code?: components["schemas"]["ReasonCode"] | null;
        };
        /**
         * Discipline
         * @enum {string}
         */
        Discipline: "clinician" | "nursing" | "physiotherapy" | "counselling_social_work" | "pharmacy" | "other";
        /** DocumentTokenView */
        DocumentTokenView: {
            /** Document Token */
            document_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Single Use
             * @default true
             */
            single_use: boolean;
        };
        /**
         * EditField
         * @enum {string}
         */
        EditField: "owner" | "explanation" | "resolution";
        /** Encounter */
        Encounter: {
            /** Attending Clinician Id */
            attending_clinician_id: string;
            /** Clinic Id */
            clinic_id: string;
            /** Encounter Id */
            encounter_id: string;
            /** Encounter Ref */
            encounter_ref: string;
            /** Patient Id */
            patient_id: string;
            /** Responsible Clinician Id */
            responsible_clinician_id: string | null;
            /** Setting */
            setting: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** EncounterListItem */
        EncounterListItem: {
            /** Encounter Id */
            encounter_id: string;
            /** Encounter Ref */
            encounter_ref: string;
            /** Patient Label */
            patient_label: string;
            /** Responsible Clinician Id */
            responsible_clinician_id: string | null;
            /** Setting */
            setting: string;
        };
        /** EncounterView */
        EncounterView: {
            encounter: components["schemas"]["Encounter"];
            /** Memberships */
            memberships: components["schemas"]["CareTeamMembership"][];
            /** Patient Label */
            patient_label: string;
            /** Sources */
            sources: components["schemas"]["SourceView"][];
            /** Staff */
            staff: components["schemas"]["Staff"][];
        };
        /**
         * Evidence
         * @description Version-bound anchor. Wire name of source_version_id is note_version_id.
         *
         *     Span evidence cites a SourceVersion. ``encounter_record`` evidence (OWN-001 only) cites a
         *     structured encounter field instead: no source version, no span, no quote. It is never a
         *     fake anchor on some note.
         */
        Evidence: {
            /** End */
            end: number;
            /**
             * Evidence Revision
             * @default 1
             */
            evidence_revision: number;
            /** Note Version Id */
            note_version_id: string | null;
            /** Page */
            page?: number | null;
            /** Quote */
            quote: string;
            /** Quote Sha256 */
            quote_sha256: string;
            record_field?: components["schemas"]["RecordField"] | null;
            role_in_flag: components["schemas"]["EvidenceRole"];
            /** Start */
            start: number;
        };
        /**
         * EvidenceRef
         * @description Points at one cited span, e.g. the allergy entry a clinician confirms as correct.
         *     Clients hold evidence, never assertion ids; the engine maps a ref to its assertion(s).
         */
        EvidenceRef: {
            /** End */
            end: number;
            /** Note Version Id */
            note_version_id: string;
            /** Start */
            start: number;
        };
        /**
         * EvidenceRole
         * @enum {string}
         */
        EvidenceRole: "claim" | "counter_claim" | "origin" | "suppressor" | "trigger" | "extraction_gap" | "missing_response_window" | "encounter_record";
        /**
         * ExtractionStatus
         * @enum {string}
         */
        ExtractionStatus: "complete" | "partial" | "no_text_layer" | "failed" | "not_applicable";
        /**
         * FeedbackEvent
         * @description Append-only. No clinical content.
         */
        FeedbackEvent: {
            action: components["schemas"]["DecisionAction"];
            actor_role: components["schemas"]["Role"];
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Corrected Owner Staff Id */
            corrected_owner_staff_id?: string | null;
            /** Feedback Id */
            feedback_id: string;
            /** Flag Id */
            flag_id: string;
            reason_code?: components["schemas"]["ReasonCode"] | null;
            rule_id: components["schemas"]["RuleId"];
            /** Rule Version */
            rule_version: number;
            /** Ruleset Version */
            ruleset_version: string;
            /** Time On Screen Ms */
            time_on_screen_ms?: number | null;
            usefulness?: components["schemas"]["Usefulness"] | null;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Corrected Owner Staff Id */
            corrected_owner_staff_id?: string | null;
            /** Flag Id */
            flag_id: string;
            /** Time On Screen Ms */
            time_on_screen_ms?: number | null;
            usefulness: components["schemas"]["Usefulness"];
        };
        /**
         * Flag
         * @description Serialises to the appendix flag JSON exactly, plus additive fields.
         */
        Flag: {
            /**
             * Affected Contributor Ids
             * @default []
             */
            affected_contributor_ids: string[];
            category: components["schemas"]["FlagCategory"];
            /** Check Version */
            check_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Evidence Revision */
            evidence_revision: number;
            /** First Run Id */
            first_run_id: string;
            /** Flag Id */
            flag_id: string;
            /** Last Run Id */
            last_run_id: string;
            lens: components["schemas"]["Lens"];
            /**
             * New Evidence Since Decision
             * @default false
             */
            new_evidence_since_decision: boolean;
            /** Owner Staff Id */
            owner_staff_id: string;
            /** Question */
            question?: string | null;
            /**
             * Ready For Clinician
             * @default false
             */
            ready_for_clinician: boolean;
            /** Reason */
            reason: string;
            /** Revision */
            revision: number;
            rule_id: components["schemas"]["RuleId"];
            /**
             * Source Changed Since Flag
             * @default false
             */
            source_changed_since_flag: boolean;
            state: components["schemas"]["FlagState"];
            /** Subject Key */
            subject_key: string;
            tier: components["schemas"]["Tier"];
            /** Title */
            title: string;
        };
        /**
         * FlagCategory
         * @description Wire ``category`` values (kebab-case, as in the appendix example).
         * @enum {string}
         */
        FlagCategory: "critical-observation-unacknowledged" | "allergy-conflict" | "dose-discrepancy" | "unparsed-dose" | "pending-action-owner-timing" | "incomplete-extraction" | "possible-copied-forward-text" | "no-responsible-clinician" | "reassurance-after-deterioration" | "laterality-conflict" | "incomplete-metadata" | "no-next-step";
        /** FlagDetail */
        FlagDetail: {
            /** Decisions */
            decisions: components["schemas"]["Decision"][];
            flag: components["schemas"]["Flag"];
            /** Revisions */
            revisions: components["schemas"]["FlagRevision"][];
        };
        /** FlagRevision */
        FlagRevision: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Decision Id */
            decision_id: string | null;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Evidence Revision */
            evidence_revision: number;
            /** Owner Staff Id */
            owner_staff_id: string;
            /** Revision */
            revision: number;
            /** Run Id */
            run_id: string | null;
            state: components["schemas"]["FlagState"];
        };
        /**
         * FlagState
         * @enum {string}
         */
        FlagState: "open" | "accepted" | "edited" | "dismissed" | "resolved" | "superseded";
        /**
         * GlanceView
         * @description Top strip (Section 13): computed server-side; the UI only renders it.
         */
        GlanceView: {
            closure_status: components["schemas"]["ClosureStatus"];
            /**
             * Cutoff
             * Format: date-time
             */
            cutoff: string;
            /** Encounter Id */
            encounter_id: string;
            /** Open Tier1 */
            open_tier1: number;
            /** Open Tier2 */
            open_tier2: number;
            /** Open Tier3 */
            open_tier3: number;
            /** Tier1 Owner Ids */
            tier1_owner_ids: string[];
            /** Top Bubble Ids */
            top_bubble_ids: string[];
            /** Top Bubble Statuses */
            top_bubble_statuses: components["schemas"]["BubbleStatus"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Lens
         * @enum {string}
         */
        Lens: "consistency" | "continuity" | "completeness" | "contradiction" | "closure";
        /**
         * LoginRequest
         * @description Synthetic login for the demonstrator: pick a synthetic staff member.
         */
        LoginRequest: {
            /** Staff Id */
            staff_id: string;
        };
        /** PageSpan */
        PageSpan: {
            /** Char Count */
            char_count: number;
            /** End */
            end: number;
            /** Page */
            page: number;
            /** Start */
            start: number;
        };
        /**
         * PreparedCheck
         * @description What a non-clinician attaches when marking a flag ready for clinician (L16).
         * @enum {string}
         */
        PreparedCheck: "pharmacy_check_attached" | "patient_verified" | "source_document_checked" | "manual_pdf_review_done";
        /** QuestionBubble */
        QuestionBubble: {
            absence?: components["schemas"]["AbsenceFinding"] | null;
            /** Bubble Id */
            bubble_id: string;
            /**
             * Cutoff
             * Format: date-time
             */
            cutoff: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Flag Id */
            flag_id?: string | null;
            /** Question */
            question: string;
            /** Question Template Id */
            question_template_id: string;
            /** Rank */
            rank: number;
            status: components["schemas"]["BubbleStatus"];
            /** Subject Key */
            subject_key: string;
            /** Uncertainty Note */
            uncertainty_note: string;
        };
        /**
         * ReasonCode
         * @description Fixed reason codes (L15). Which codes each action allows is in permissions.py.
         * @enum {string}
         */
        ReasonCode: "extraction_error" | "already_addressed_in_source" | "wrong_encounter" | "duplicate_of" | "not_clinically_relevant" | "response_documented_confirmed" | "allergy_entry_confirmed" | "intolerance_not_allergy" | "dose_entry_current" | "owner_and_timing_documented" | "manual_review_completed" | "ocr_completed" | "statement_confirmed_current" | "statement_corrected_in_source" | "work_completed_documented";
        /**
         * RecordField
         * @description Structured encounter fields an ``encounter_record`` evidence item may name.
         * @enum {string}
         */
        RecordField: "encounter.responsible_clinician_id";
        /**
         * Role
         * @description System (authorisation) role of a staff member. Distinct from Discipline,
         *     which describes a source document, and from TeamRole.
         * @enum {string}
         */
        Role: "clinician" | "nurse" | "pharmacist" | "allied_health" | "clerical_staff" | "clinic_admin" | "medical_director" | "quality_risk" | "legal";
        /**
         * RuleId
         * @description Rule catalog (Section 8.2). MVP rules are enabled in rulesets/v1.json;
         *     stretch rules exist here so their wire values are frozen, and are disabled
         *     in v1 until a CCR adds golden expectations for them.
         * @enum {string}
         */
        RuleId: "CRIT-001" | "ALG-001" | "DOSE-001" | "DOSE-002" | "PEND-001" | "PDF-001" | "DIFF-001" | "OWN-001" | "DET-001" | "LAT-001" | "META-001" | "NEXT-001";
        /** SearchedSource */
        SearchedSource: {
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Note Version Id */
            note_version_id: string;
        };
        /** SessionView */
        SessionView: {
            discipline: components["schemas"]["Discipline"];
            /** Display Name */
            display_name: string;
            role: components["schemas"]["Role"];
            /** Staff Id */
            staff_id: string;
        };
        /** SourceText */
        SourceText: {
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Note Version Id */
            note_version_id: string;
            /**
             * Pages
             * @default []
             */
            pages: components["schemas"]["PageSpan"][];
            /** Text */
            text: string;
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "pasted_text" | "pdf" | "fhir_documentreference" | "hl7v2" | "cda" | "transcript_segment";
        /**
         * SourceView
         * @description Metadata only (no text). Text is fetched per version via SOURCE_TEXT.
         */
        SourceView: {
            /** Author Staff Id */
            author_staff_id: string;
            discipline: components["schemas"]["Discipline"];
            /** Extraction Note */
            extraction_note?: string | null;
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Note Version Id */
            note_version_id: string;
            /**
             * Page Count
             * @default 0
             */
            page_count: number;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Sha256 */
            sha256: string;
            /** Source Id */
            source_id: string;
            /**
             * Source Time
             * Format: date-time
             */
            source_time: string;
            source_type: components["schemas"]["SourceType"];
            /** Supersedes Version Id */
            supersedes_version_id: string | null;
            /** Title */
            title: string;
            /** Version */
            version: number;
            /**
             * Version Time
             * Format: date-time
             */
            version_time: string;
        };
        /** Staff */
        Staff: {
            /** Clinic Id */
            clinic_id: string;
            discipline: components["schemas"]["Discipline"];
            /** Display Name */
            display_name: string;
            role: components["schemas"]["Role"];
            /** Staff Id */
            staff_id: string;
        };
        /**
         * StaleRevision
         * @description 409 body extension: current state and the other actor's decision (feedback 10).
         */
        StaleRevision: {
            /** Current Revision */
            current_revision: number;
            current_state: components["schemas"]["FlagState"];
            /**
             * Error Code
             * @default stale_revision
             * @constant
             */
            error_code: "stale_revision";
            last_decision_action?: components["schemas"]["DecisionAction"] | null;
            /** Last Decision Actor Staff Id */
            last_decision_actor_staff_id?: string | null;
            /** Last Decision At */
            last_decision_at?: string | null;
        };
        /** Summary */
        Summary: {
            /** Claims */
            claims: components["schemas"]["SummaryClaim"][];
            closure_status: components["schemas"]["ClosureStatus"];
            /**
             * Cutoff
             * Format: date-time
             */
            cutoff: string;
            /** Encounter Id */
            encounter_id: string;
            /** Encounter Ref */
            encounter_ref: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Human Review Statement
             * @default Requires human review. Not the medical record. Does not diagnose or recommend treatment.
             * @constant
             */
            human_review_statement: "Requires human review. Not the medical record. Does not diagnose or recommend treatment.";
            /** Patient Ref */
            patient_ref: string;
            /** Registry Version */
            registry_version: string;
            /** Ruleset Version */
            ruleset_version: string;
            /**
             * Stale After Source Change
             * @default false
             */
            stale_after_source_change: boolean;
            /** Timeline */
            timeline: components["schemas"]["TimelineEntry"][];
        };
        /**
         * SummaryClaim
         * @description Every claim is a deterministic template over flag/decision/bubble records,
         *     with evidence. No free paraphrase.
         */
        SummaryClaim: {
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Params */
            params: {
                [key: string]: string | number;
            };
            template: components["schemas"]["SummaryClaimTemplate"];
            /** Text */
            text: string;
        };
        /**
         * SummaryClaimTemplate
         * @enum {string}
         */
        SummaryClaimTemplate: "open_priority" | "decision_record" | "top_question";
        /**
         * TeamRole
         * @enum {string}
         */
        TeamRole: "responsible_clinician" | "attending" | "member";
        /**
         * Tier
         * @enum {integer}
         */
        Tier: 1 | 2 | 3;
        /** TimelineEntry */
        TimelineEntry: {
            /** Author Staff Id */
            author_staff_id: string;
            discipline: components["schemas"]["Discipline"];
            extraction_status: components["schemas"]["ExtractionStatus"];
            /** Note Version Id */
            note_version_id: string;
            /** Source Id */
            source_id: string;
            /**
             * Source Time
             * Format: date-time
             */
            source_time: string;
            source_type: components["schemas"]["SourceType"];
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /**
         * Usefulness
         * @enum {string}
         */
        Usefulness: "useful" | "not_useful" | "wrong_owner" | "stale_wording" | "missing_rule";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkspaceInfo
         * @description The workspace token lives only in JS memory (Section 6.3).
         */
        WorkspaceInfo: {
            /** Encounter Ids */
            encounter_ids: string[];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Single Process Store
             * @default true
             * @constant
             */
            single_process_store: true;
            /** Workspace Token */
            workspace_token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    aggregate_api_aggregate_risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_status_api_ai_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIStatusView"];
                };
            };
        };
    };
    get_document_api_documents__document_token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_token: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_encounters_api_encounters_get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path?: never;
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_encounter_api_encounters__encounter_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bubbles_api_encounters__encounter_id__bubbles_get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BubbleList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_checks_api_encounters__encounter_id__check_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_run_api_encounters__encounter_id__check_runs_latest_get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_closure_api_encounters__encounter_id__closure_get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosureView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attempt_close_api_encounters__encounter_id__closure_post: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosureView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_api_encounters__encounter_id__feedback_post: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_flags_api_encounters__encounter_id__flags_get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flag"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_flag_api_encounters__encounter_id__flags__flag_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
                flag_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_encounters__encounter_id__flags__flag_id__decisions_post: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
                flag_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagDetail"];
                };
            };
            /** @description stale_revision: StaleRevision body (current state and the other actor's decision). invalid_transition: {error_code} only; branch on error_code. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaleRevision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_glance_api_encounters__encounter_id__glance_get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlanceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_token_api_encounters__encounter_id__source_versions__source_version_id__document_token_post: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
                source_version_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentTokenView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_text_api_encounters__encounter_id__source_versions__source_version_id__text_get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
                source_version_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceText"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_text_source_api_encounters__encounter_id__sources_post: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTextSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_pdf_source_api_encounters__encounter_id__sources_pdf_post: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_pdf_source_api_encounters__encounter_id__sources_pdf_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_encounters__encounter_id__summary_get: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path: {
                encounter_id: string;
            };
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    current_session_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    new_workspace_api_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_workspace_api_workspaces_current_delete: {
        parameters: {
            query?: never;
            header?: {
                "x-workspace-token"?: string | null;
            };
            path?: never;
            cookie?: {
                ng_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const aIDraftStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["AIDraftStatus"]> = ["disabled", "unavailable_fallback", "rejected_fallback", "validated"];
export const absenceFindingStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["AbsenceFinding"]["status"]> = ["not_documented_in_supplied_sources", "incomplete_extraction"];
export const bubbleStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["BubbleStatus"]> = ["documented", "not_documented_in_supplied_sources", "conflicting", "incomplete_extraction", "requires_human_review"];
export const changeKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ChangeKind"]> = ["new", "explicit_change", "reworded", "carried_forward", "removed"];
export const checkRunOutcomeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CheckRunOutcome"]> = ["completed", "completed_with_extraction_gaps", "failed"];
export const closureStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ClosureStatus"]> = ["blocked", "clear_with_open_tier2", "clear"];
export const decisionActionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["DecisionAction"]> = ["accept", "edit", "reassign", "mark_ready_for_clinician", "dismiss", "resolve"];
export const disciplineValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Discipline"]> = ["clinician", "nursing", "physiotherapy", "counselling_social_work", "pharmacy", "other"];
export const editFieldValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["EditField"]> = ["owner", "explanation", "resolution"];
export const evidenceRoleValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["EvidenceRole"]> = ["claim", "counter_claim", "origin", "suppressor", "trigger", "extraction_gap", "missing_response_window", "encounter_record"];
export const extractionStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ExtractionStatus"]> = ["complete", "partial", "no_text_layer", "failed", "not_applicable"];
export const flagCategoryValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["FlagCategory"]> = ["critical-observation-unacknowledged", "allergy-conflict", "dose-discrepancy", "unparsed-dose", "pending-action-owner-timing", "incomplete-extraction", "possible-copied-forward-text", "no-responsible-clinician", "reassurance-after-deterioration", "laterality-conflict", "incomplete-metadata", "no-next-step"];
export const flagStateValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["FlagState"]> = ["open", "accepted", "edited", "dismissed", "resolved", "superseded"];
export const lensValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Lens"]> = ["consistency", "continuity", "completeness", "contradiction", "closure"];
export const preparedCheckValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["PreparedCheck"]> = ["pharmacy_check_attached", "patient_verified", "source_document_checked", "manual_pdf_review_done"];
export const reasonCodeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ReasonCode"]> = ["extraction_error", "already_addressed_in_source", "wrong_encounter", "duplicate_of", "not_clinically_relevant", "response_documented_confirmed", "allergy_entry_confirmed", "intolerance_not_allergy", "dose_entry_current", "owner_and_timing_documented", "manual_review_completed", "ocr_completed", "statement_confirmed_current", "statement_corrected_in_source", "work_completed_documented"];
export const recordFieldValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RecordField"]> = ["encounter.responsible_clinician_id"];
export const roleValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Role"]> = ["clinician", "nurse", "pharmacist", "allied_health", "clerical_staff", "clinic_admin", "medical_director", "quality_risk", "legal"];
export const ruleIdValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RuleId"]> = ["CRIT-001", "ALG-001", "DOSE-001", "DOSE-002", "PEND-001", "PDF-001", "DIFF-001", "OWN-001", "DET-001", "LAT-001", "META-001", "NEXT-001"];
export const sourceTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SourceType"]> = ["pasted_text", "pdf", "fhir_documentreference", "hl7v2", "cda", "transcript_segment"];
export const summaryClaimTemplateValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SummaryClaimTemplate"]> = ["open_priority", "decision_record", "top_question"];
export const teamRoleValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TeamRole"]> = ["responsible_clinician", "attending", "member"];
export const tierValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Tier"]> = [1, 2, 3];
export const usefulnessValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Usefulness"]> = ["useful", "not_useful", "wrong_owner", "stale_wording", "missing_rule"];
